### ISSUE TITLE
one problem

### ISSUE THREAD

**Issue by BX-xb** [MathAI-LAB/PTMDA#1]
Hi ,thank you for your good work , I can not find MN used in your code, can you give an example?
self.bn1 = model_resnet.bn1. 
It seems BN layers are not replaced with the MN layers.
And ''import resnet_tn7 as resnet_tn", I cannot find resnet_tn7 in the folder.

**Comment by AIlearner1** [comment]
Thank you for your interest in our paper.
1. The file "BNs9.py" contains the code for MN. 
 The   BN layers are replaced with the MN layers. 
See  "from BNs9 import SBatchNorm2d " in "resnet_tn7_2.py ".

2. "resnet_tn7_2.py" is added.

**Comment by Gumpliu404** [comment]
您好，我想请问一下您在Fea_WD2a2代码中，在dsets["test"]里读入了数据，但是您设置的类别数为10，但是amazon的类别数有31个，而且在图像处理函数里也只有10个transform，我刚涉及迁移学习领域，对您的论文理解可能不够深，请问这里为什么是10个类别呢，是您在office10上做的实验吗，因为在train1s里您用的是31类的amazon
